# Generated by Django 4.2.2 on 2023-06-10 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('headset_type', models.CharField(choices=[('Oculus Rift', 'Oculus Rift'), ('HTC Vive', 'HTC Vive'), ('PlayStation VR', 'PlayStation VR'), ('Meta Quest', 'Meta Quest'), ('Other', 'Other')])),
                ('duration_of_use', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motion_sickness', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('immersion_level', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
        ),
    ]
