# Generated by Django 4.2.2 on 2023-06-10 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration_of_use',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
